image: node:18.15.0

stages:
  - install
  - test1
  - test2
  - deploy

install:
  stage: install
  only:
    refs:
    - main
  script:
    - yarn install
  artifacts:
    paths:
    - node_modules/
  cache:
    paths:
    - node_modules/

test1:
  stage: test1
  only:
    refs:
    - main
  script:
    - yarn test

test2:
  image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1
  stage: test2
  only:
    refs:
    - main
  script:
    - yarn add cypress
    - PORT=3000 yarn start &
    - yarn run wait-on http://localhost:3000
    - yarn cypress:run

deploy:
  stage: deploy
  only:
    refs:
    - main
  script:
    - yarn build
    - yarn global add firebase-tools
    - firebase deploy --token $FIREBASE_TOKEN