image: node:18.15.0

stages:
  - install
  - test
  - deploy

install:
  stage: install
  only:
    refs:
    - main
  script:
    - yarn install
  artifacts:
    paths:
    - node_modules/
  cache:
    paths:
    - node_modules/

test:
  stage: test
  only:
    refs:
    - main
  script:
    - apt-get install xvfb
    - yarn test
    - yarn run cypress install
    - PORT=3000 yarn start &
    - wait-on http://localhost:3000
    - yarn cypress:run

deploy:
  stage: deploy
  only:
    refs:
    - main
  script:
    - yarn build
    - yarn global add firebase-tools
    - firebase deploy --token $FIREBASE_TOKEN