apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: tetsu-n--game
build:
  artifacts:
    - image: game
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - k8s/deployment.yaml
    - k8s/ingress.yaml
    - k8s/service.yaml
