apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tetsu19n1101087-game-ingress
spec:
  rules:
    - host: tetsu19n1101087-game.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tetsu19n1101087-game-service
                port:
                  number: 3000