apiVersion: v1
kind: Service
metadata:
  name: tetsu19n1101087-game-service
spec:
  type: NodePort
  selector:
    app: react
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000