apiVersion: v1
kind: Service
metadata:
  name: tetsu19n1101087-api-service
spec:
  type: NodePort
  selector:
    app: express
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30001